### ISSUE TITLE
more example functions

### ISSUE THREAD

**Issue by that-ugly-cat** [Fingertips/SWITCHtube-examples#3]
Hello, 
I had to do pythonic stuff with the apis and based on the provided examples I've put together a small set of functions for the most basic activities (listing channels, listing content of channels, uploading videos, deleting videos). 

Maybe it can save time to someone else, so I'll leave it to you guys :
[switchtube_functions.txt](https://github.com/Fingertips/SWITCHtube-examples/files/8133828/switchtube_functions.txt)

**Comment by tvandervossen** [comment]
Thank you for showing how you used the API. The goal of the usage examples is illustrate how to get started, not to offer a complete client implementation.
