### ISSUE TITLE
oembed, available?

### ISSUE THREAD

**Issue by benzkji** [Fingertips/SWITCHtube-examples#5]
Does switchtube provide an oembed endpoint?  
That would help a lot, when creating iframes embeds from an url only, no need to parse the url, to find the id, etc, etc.

**Comment by tvandervossen** [comment]
Switch Tube doesn’t provide oEmbed currently. If you’d like to see this added, please email any of the people listed on https://www.switch.ch/en/tube to request it as a feature. If you are working for or with an organization that’s a Switch Tube customer, it might help to mention that explicitly.

**Comment by benzkji** [comment]
thanks for the quick reply, will do so.
